sequence_file: sequences.fasta
protocol: sequence_to_class
model_choice: FNN
optimizer_choice: adam
loss_choice: cross_entropy_loss
num_epochs: 200
use_class_weights: False
learning_rate: 1e-3
batch_size: 128
embedder_name: one_hot_encoding
embeddings_file: http://www.your-domain.com/embeddings_file.h5