sequence_file: sequences.fasta
labels_file: labels.fasta
mask_file: mask.fasta
protocol: residue_to_class
model_choice: CNN
optimizer_choice: adam
loss_choice: cross_entropy_loss
num_epochs: 200
use_class_weights: False
learning_rate: 1e-3
batch_size: 128
embedder_name: one_hot_encoding